services:
  ollama:
    image: ollama/ollama:${DOCKER_OLLAMA_TAG-latest}
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    volumes:
      - local-ollama:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:${DOCKER_WEBUI_TAG-main}
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
    volumes:
      - local-open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  runner_pytorch:
    container_name: ${PROJECT_NAME}_runner_pytorch
    build: 
      context: ./Apps/runner-pytorch
      dockerfile: Dockerfile
    runtime: nvidia
    ipc: host  # Para compartir memoria entre procesos en multihilo
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: bash
    volumes:
      - ./Apps/runner-pytorch/workspace:/workspace
  
  runner_tensorflow:
    container_name: ${PROJECT_NAME}_runner_tensorflow
    build: 
      context: ./Apps/runner-tensorflow
      dockerfile: Dockerfile
    runtime: nvidia
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: bash
    volumes:
      - ./Apps/runner-tensorflow/workspace:/workspace

volumes:
  local-ollama:
    external: false
  local-open-webui:
    external: false


    