services:
  ollama:
    image: ollama/ollama:${DOCKER_OLLAMA_TAG-latest}
    container_name: ${PROJECT_NAME}_ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    volumes:
      - local-ollama:/root/.ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: 
                - gpu

  open-webui:
    image: ghcr.io/open-webui/open-webui:${DOCKER_WEBUI_TAG-main}
    container_name: ${PROJECT_NAME}_open-webui
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - "WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}"
    volumes:
      - local-open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  runner_pytorch:
    container_name: ${PROJECT_NAME}_runner_pytorch
    image: nvcr.io/nvidia/pytorch:25.01-py3 
    # build:
    #   context: ./Apps/runner-1-pytorch
    #   dockerfile: Dockerfile
    command: bash
    stdin_open: true
    tty: true
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./Apps/runner-1-pytorch/workspace_pytorch:/workspace_pytorch:ro
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  runner_tensorflow:
    container_name: ${PROJECT_NAME}_runner_tensorflow
    image: nvcr.io/nvidia/tensorflow:25.01-tf2-py3
    # build:
    #   context: ./Apps/runner-2-tensorflow
    #   dockerfile: Dockerfile
    #   args:
    #     - ENV_SIMIDAT=simidat
    command: bash
    # Comentar en windows
    # user: "${UID}:${GID}" 
    stdin_open: true
    tty: true
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./Apps/runner-2-tensorflow/workspace_tensorflow:/workspace_tensorflow
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  runner_rapidsai:
    container_name: ${PROJECT_NAME}_runner_rapidsai-notebook
    image: nvcr.io/nvidia/rapidsai/notebooks:24.12-cuda12.5-py3.12
    #build:
    #  context: ./Apps/runner-3-rapidsai
    #  dockerfile: Dockerfile
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
    ipc: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # - EXTRA_CONDA_PACKAGES=beautifulsoup4
      # - CONDA_TIMEOUT=5
      # - EXTRA_PIP_PACKAGES=tabulate
      # - PIP_TIMEOUT=5
    # configuración de  RapidsAI
    pull_policy: always
    shm_size: 1gb
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./Apps/runner-3-rapidsai/workspace_rapidsai:/workspace_rapidsai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: 
                - gpu

volumes:
  local-ollama:
    external: false
  local-open-webui:
    external: false
