
FROM nvcr.io/nvidia/pytorch:25.01-py3


ENV HOST=docker
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
# https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG USERNAME=ubuntu
# ARG USER_UID=1000
# ARG USER_GID=1000

#
# [Optional] Add sudo support. Omit if you don't need to install software after connecting.
RUN apt-get update
RUN apt-get install -y sudo
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
RUN chmod 0440 /etc/sudoers.d/$USERNAME


RUN apt-get update

RUN apt-get install -y --no-install-recommends apt-utils dialog 2>&1
RUN apt-get install -y --no-install-recommends htop
RUN apt-get install -y --no-install-recommends nvtop
RUN apt-get install -y --no-install-recommends zip unzip
RUN apt-get install -y --no-install-recommends tzdata
RUN apt-get install -y --no-install-recommends fonts-powerline
# ZSH
RUN apt-get install -y --no-install-recommends zsh

USER $USERNAME

#RUN chsh -s /bin/zsh
# RUN chsh -s $(which zsh) dev-user

# Install oh-my-zsh
RUN yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions.git              ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN git clone --depth 1 https://github.com/marlonrichert/zsh-autocomplete.git             ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autocomplete
RUN git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git          ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
RUN git clone --depth 1 https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting

RUN sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting zsh-autocomplete docker)/' ~/.zshrc 

RUN pip install --upgrade pip
RUN pip3 install --upgrade nvitop

# WORKDIR /workspaces_devcontainer
# ENV SHELL=/bin/zsh
