
FROM nvcr.io/nvidia/pytorch:25.01-py3


ENV HOST=docker
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
# https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


RUN apt-get update

RUN apt-get install -y --no-install-recommends htop
RUN apt-get install -y --no-install-recommends nvtop
RUN apt-get install -y --no-install-recommends zip
RUN apt-get install -y --no-install-recommends unzip
RUN apt-get install -y --no-install-recommends zsh
RUN apt-get install -y --no-install-recommends tzdata
RUN apt-get install -y --no-install-recommends fonts-powerline

# Install oh-my-zsh
#RUN chsh -s /bin/zsh
RUN chsh -s $(which zsh) root

RUN yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# RUN sed -i 's/plugins=(git)/plugins=(git vi-mode)/' /root/.zshrc # ohmyzsh plugins

RUN pip install --upgrade pip
RUN pip3 install --upgrade nvitop


# WORKDIR /workspaces_devcontainer
# ENV SHELL=/bin/zsh
